### ISSUE TITLE
Docs: Clarify VALIDATE vs AUTHENTICATE methods for trusting client certificates

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan-operator#1188]
VALIDATE allows Infinispan to trust client certificates that are CA signed. Requires a separate authn mechanism to actually authenticate Infinispan credentials (DIGEST, SCRAM ...)

AUTHENTICATE requires clients to present a public certificate that is signed and contains client credentials (cn field). Requires clients to use EXTERNAL sasl mech.

**Comment by tristantarrant** [comment]
Correction: certificates always have a "name" (a distinguished name or `DN`). The common name (or `CN`) is usually the first part of the DN that is sufficient to uniquely identify a name from another (although there is no strict requirement that a CN is unique across the whole namespace).
In order for VALIDATE to work, it is sufficient that that trust store contains any part of the chain that has signed the client certificates (using the Root CA is usually the easiest, since it will trust all certificates signed by it).
In order for AUTHENTICATE to work, the truststore must contain all of the client certificates and not just the CA.
