### ISSUE TITLE
Why do you use Infinispan

### ISSUE THREAD

**Issue by HelloTo4x** [infinispan/infinispan-operator#1559]
Hi, i am reading your project, why do you use Infinispan for caching instead of Redis, can you tell me why you choose it, and the pros and cons of this, thank u so much

**Comment by ryanemerson** [comment]
Hi @HelloTo4x thanks for the interest in the project. There's many features/capabilities that differentiate Infinispan from Redis, below are just some highlights:

- All Infinispan components are fully open-source [Apache-2.0 license](https://github.com/infinispan/infinispan-operator/blob/main/LICENSE). Whereas Redis is only open-core, with advanced features such as the Kubernetes Operator, Cross-site replication, Backup/Restore requiring Redis Enterprise
- [Configurable consistency guarantees](https://infinispan.org/docs/stable/titles/configuring/configuring.html#partition-handling), whereas Redis does not allow for strong consistency.
- Browser based Management console
- Kubectl native CLI plugin
- [Official Helm Charts](https://github.com/infinispan/infinispan-helm-charts)
- [Embedded mode](https://infinispan.org/docs/stable/titles/configuring/configuring.html#creating-embedded-caches)
- [Simple caching of SQL database tables and queries](https://infinispan.org/docs/stable/titles/configuring/configuring.html#sql-cache-store_persistence)
- Enterprise security integrations with LDAP and SSO providers such as Keycloak
- From Infinispan 14, a [RESP](https://redis.io/docs/reference/protocol-spec/) is provided so that existing Redis clients can be used with an Infinispan cluster.
- [Interoperable Hot Rod, REST, RESP and Memcached connectivity](https://infinispan.org/docs/stable/titles/server/server.html#server-endpoints)
- Windows support
