### ISSUE TITLE
Upgrade to operator-sdk 1.0

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#562]
[Version 1.0](https://www.openshift.com/blog/operator-sdk-reaches-v1.0)  of the operator-sdk has been released and greatly simplifies the api, removing the need for a lot of boiler plate. We should upgrade our code to be based upon this.

**Comment by dmvolod** [comment]
Yes, @ryanemerson, it would be nice, also #510 awaiting for the this version. But it binds at very high k8s version and limits operator to be running on previous k8s/OCP/OKD versions.
Do you know about k8s/OCP/OKD compatibility plans for latest operator release?

**Comment by ryanemerson** [comment]
@dmvolod I'm not sure what our downstream support plans are atm, but that will definitely determine when this upgrade is possible. I'll try to find this information out next week.

 Do you know what versions of k8s/OCP/OKD the `v1.0.0` of the SDK requires?

**Comment by dmvolod** [comment]
@ryanemerson , operator SDK relates to k8s 0.18.x
I point your corporate email on the document, that @rigazilla shared with me.

**Comment by ryanemerson** [comment]
@dmvolod thanks

**Comment by rigazilla** [comment]
I'll follow this guide:
https://sdk.operatorframework.io/docs/building-operators/golang/migration/

**Comment by rigazilla** [comment]
using sdk 1.3.1 which should be good for k8s 1.19 and ocp 4.6

**Comment by rigazilla** [comment]
I've tried a raw import, but go.mod dependencies go wild.
I'm working on a new approach, step by step import starting from types and simple controllers first (Cache)

code is in an orphan branch here:

**Comment by rigazilla** [comment]
this tag has a working controller for cache:
https://github.com/rigazilla/infinispan-operator/tree/working-cache

**Comment by rigazilla** [comment]
tag with working batch, backup, restore
https://github.com/rigazilla/infinispan-operator/tree/working-batch-backup-restore

**Comment by rigazilla** [comment]
This [tag](https://github.com/rigazilla/infinispan-operator/tree/maintest_running) has a working operator running locally and the main testsuite running (TestNodeStartup PASS at least)

Code structure has been changed a lot to reflect SDK changes, a the point that this is more a new baseline than a PR. 

I didn't investigate the option of upgrading the operator-sdk binary without upgrading the code deps to the new SDK version. IMO it sounds like a dangerous way since I suppose the tools make some assuptions on the operator source code that could be wrong on old code...

MAIN CHANGES:
- controllers are all generated under `controllers` folder/package
- api are grouped by releases and generated under `api` folder
- `github.com/operator-framework/operator-sdk/pkg/k8sutil` no longer exists, source code has been imported under `pkg/k8sutil`
- I had a hard fight with Grafana stuff, cause it has been impossible for me to find the correct version to use. I've temporarily imported the source code for the needed types in `pkg/apis/integreatly/v1alpha1`
- `CreateOrxxx` now come from `sigs.k8s.io/controller-runtime/pkg/controller/controllerutil`
- the startup process has been updated

**Comment by ryanemerson** [comment]
> * `github.com/operator-framework/operator-sdk/pkg/k8sutil` no longer exists, source code has been imported under `pkg/k8sutil`

I believe this is still available, however it's in the `internal/k8sutil` package.

**Comment by rigazilla** [comment]
> > * `github.com/operator-framework/operator-sdk/pkg/k8sutil` no longer exists, source code has been imported under `pkg/k8sutil`
> 
> I believe this is still available, however it's in the `internal/k8sutil` package [operator-framework/operator-sdk#3475](https://github.com/operator-framework/operator-sdk/pull/3475).

yeah, I can't remember why I decided to cherry-pick only the needed code. maybe k8sutil was one of the package that made `go.mod` go wild

**Comment by rigazilla** [comment]
Missing steps:

- [ ] review and import all the `build/*.sh`
- [ ]  review RBAC (now should be generated from source code annotations)
- [ ] review how crd, cvs, example cr are now generated
- [ ] ... whatever

**Comment by dmvolod** [comment]
@rigazilla please don't forget to remove `contains` and `remove` functions in the `infinispan_controller.go` and replace them with  methods from the actual `controller-runtime`

**Comment by rigazilla** [comment]
> @rigazilla please don't forget to remove `contains` and `remove` functions in the `infinispan_controller.go` and replace them with methods from the actual `controller-runtime`

I've updated the PR (I think it's ok to use it in place of the old orphan branch)

**Comment by ryanemerson** [comment]
> * [ ]  operator warns about `W0811 19:17:48.753001 1525270 reflector.go:424] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: watch of *v1.Infinispan ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"Infinispan\" is registered for version \"infinispan.org/v1\" in scheme \"pkg/runtime/scheme.go:101\"") has prevented the request from succeeding`
> *

This is related to how we're creating the REST client. I haven't been able to get it to work yet, but a minimal operator that reproduces the issue is available at https://github.com/ryanemerson/minimal-operator

To see the same warning, connect to a k8s cluster, execute `make run` and wait for a few minutes.

**Comment by ryanemerson** [comment]
The following change in `pkg/kubernetes/kubernetes.go` fixed the issue:

```go
config.NegotiatedSerializer = serializer.WithoutConversionCodecFactory{CodecFactory: serializer.NewCodecFactory(scheme)}
```

**Comment by ryanemerson** [comment]
Upgraded to v1.3.2 #1221
